spring:
   datasource:
     driver-class-name: org.h2.Driver
     url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
     username: sa
     password:
   h2:
     console:
       path: /h2-console
       enabled: true
       settings:
         web-allow-others: true
   jpa:
     hibernate:
       ddl-auto: none
     show-sql: true
     properties:
       hibernate:
         format_sql: true
   flyway:
     enabled: true
     locations: classpath:db/migration
     baseline-on-migrate: true
     out-of-order: true
rsa:
    private-key: classpath:keys/private_key.pem
    public-key: classpath:keys/public_key.pem
