spring:
  profiles:
    active: dev
  application:
    name: workshop
  jpa:
    open-in-view: false
server:
  servlet:
    context-path: /api

rsa:
  private-key: classpath:keys/private_key.pem
  public-key:  classpath:keys/public_key.pem
