name: dev
on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create private/public keys from secrets
      run: |
        mkdir -p target/classes/keys
        echo "${{ secrets.PRIVATE_KEY }}" > target/classes/keys/private.key
        echo "${{ secrets.PUBLIC_KEY }}" > target/classes/keys/public.key
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn test -X

  test:
    needs: ['build'] 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create private/public keys from secrets
      run: |
        mkdir -p target/classes/keys
        echo "${{ secrets.PRIVATE_KEY }}" > target/classes/keys/private.key
        echo "${{ secrets.PUBLIC_KEY }}" > target/classes/keys/public.key
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run Tests
      run: mvn test
