name: dev
on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Ensure private/public keys are in the correct directory
      run: |
        # Garantir que a pasta keys existe
        mkdir -p src/main/resources/keys
        # Criar os arquivos com as chaves privadas e públicas, sobrescrevendo se existirem
        echo "${{ secrets.PRIVATE_KEY }}" > src/main/resources/keys/private.key
        echo "${{ secrets.PUBLIC_KEY }}" > src/main/resources/keys/public.key

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Compile with Maven (no tests)
      run: mvn clean package
  
  test:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Ensure private/public keys are in the correct directory
      run: |
        # Garantir que a pasta keys existe
        mkdir -p src/main/resources/keys
        # Criar os arquivos com as chaves privadas e públicas, sobrescrevendo se existirem
        echo "${{ secrets.PRIVATE_KEY }}" > src/main/resources/keys/private.key
        echo "${{ secrets.PUBLIC_KEY }}" > src/main/resources/keys/public.key

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run Tests
      run: mvn test
