name: dev
on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create private/public keys from secrets
      run: |
        mkdir -p /tmp/keys
        echo "${{ secrets.PRIVATE_KEY }}" > /tmp/keys/private.key
        echo "${{ secrets.PUBLIC_KEY }}" > /tmp/keys/public.key
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Compile with Maven (without running tests)
      run: mvn clean compile

  test:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set environment variables for keys
      run: |
        echo "KEYS_PATH=/tmp/keys" >> $GITHUB_ENV

    - name: Run Tests
      run: mvn test

    - name: Clean up keys
      run: |
        rm -rf /tmp/keys
