name: main

on:
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create private/public keys from secrets
        run: |
          mkdir -p target/classes/keys
          printf "%s\n" "${{ secrets.PRIVATE_KEY }}" > target/classes/keys/private.key
          printf "%s\n" "${{ secrets.PUBLIC_KEY }}" > target/classes/keys/public.key

      - name: Save keys as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: keys
          path: target/classes/keys

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (compiling only)
        run: mvn clean compile

  test:
    needs: ['compile']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download keys artifact
        uses: actions/download-artifact@v4
        with:
          name: keys
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn test

  build:
    needs: ['compile', 'test']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download keys artifact
        uses: actions/download-artifact@v4
        with:
          name: keys

      - name: Move keys to target/classes/keys
        run: |
          mkdir -p target/classes/keys
          mv keys/* target/classes/keys/

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (packaging)
        run: mvn clean package
